type User {
    id: Int,
    firstName:String
    lastName:String
    isActive:Boolean
    email: String
	password: String
}

type UserData {
    token:String,
    data:User
}


type Query{
    userLogin(email:String!, password:String!): UserData
}

type Mutation{
    createUser(email:String!, password:String!, firstName:String!, lastName:String!): User
}