type User {
    id: Int,
    firstName:String
    lastName:String
    isActive:Boolean
    email: String
	password: String
}


type Query{
    userLogin(email:String!, password:String!): User
}

type Mutation{
    createUser(email:String!, password:String!, firstName:String!, lastName:String!): User
}